version: "2"
services:
    backend-app:
        image: oneeg/php:7.2-apache
        volumes:
            - $APP_PATH:/app
        ports:
            - $APP_HOST_PORT:80
        env_file:
          - $APP_PATH/.env

    backend-mongo:
        image: mongo
        ports:
            - $MONGO_HOST_PORT:27017
        volumes:
            - './backend/mongod.conf:/etc/mongod.conf'
            - './backend/dump:/dump'
        command:
            - 'mongod'
            - '-f'
            - '/etc/mongod.conf'

    panel-app:
        image: node:9.4.0-alpine
        volumes:
            - $PANEL_PATH:/panel
        working_dir:
            "/panel"
        ports:
          - $PANEL_HOST_PORT:3002
        command: npm run docker 
